branches:
  only:
    - master

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%APPDATA%\npm'

install:
  - git submodule update --init --recursive
  - ps: Install-Product node 6 x64
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
  - npm prune
  - npm install

before_build:
  - node --version
  - npm --version
  - npm run test

build_script:
  - npm run publish-win

test: off
