platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 6 x64
  - npm -g install npm@next
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - npm prune

build: off

test_script:
  - node --version
  - npm --version
  - npm run test
