environment:
  GH_TOKEN:
    secure: aHR/oHfCV08nk3sEPkU9TwQCMkH9q8T4p35GsiRiEeld7VTN86waeiADM6oQkfuE

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%APPDATA%\npm'

install:
  - ps: Install-Product node 6 x64
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
  - npm install
  - npm prune

test_script:
  - node --version
  - npm --version
  - npm run test

build_script:
  - npm run publish-win
